added HW 37-40
Dmirovna90/Blogfolio_NEW pull request #1
Opened 2024-12-12 16:43 UTC by Dmirovna90

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/Button/Button.tsx
> +    buttonType?: 'primary' | 'secondary' | 'secondary2';
need add onClick function

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/Title/Title.module.scss
> +    // margin: auto;
comment

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/Title/Title.tsx
> +        </div>
better use 
`return (
        {!!titile && <div>
            <p className = {style.title}>{title}</p>
        </div>
        }
    )`

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/Title/Title.tsx
> +    if (title === undefined) {
remove children in this component

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/AddPost/AddPost.tsx
> +            {/* <div className = {style.addpost}>
i don't undestand what should do this component

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/Footer/Footer.tsx
> +                    ©2024 Blogfolio
use Data to calculate the year

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/Input/Input.tsx
> +const Input = ({title, type = 'text', placeholder = "Placeholder"}: IProps) => {
you should add onChange function in props

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/InputOutput/InputOutput.tsx
> +    if (title === undefined) {
reemove children

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/Tabs/Tabs.tsx
> +// const Tabs = () => {
remove comented code

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Components/TextArea/TextArea.tsx
> +const Input = ({title, placeholder = "Placeholder"}: IProps) => {
you should add onChange function in props

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Pages/SignIn/SignIn.tsx
> +        <>
what to do Fragment in this case?

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Pages/SignUp/SignUp.tsx
> +        <>
what to do Fragment in this case?

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Pages/Home/Home.tsx
> +            {/* <Input title = {'Name'} placeholder = {'Your name'} type = {'password'}/> */}
remove comment

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Pages/AllPosts/AllPosts.tsx
> +// import { useNavigate } from "react-router-dom";
comment

2024-12-15 22:56 UTC, PavelYermakov1 commented on my-app/src/Pages/AllPosts/AllPosts.tsx
> +    const [results, setPosts] = useState([]);
useState must be similar name variable and function like `[result, setResult]`

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Components/Button/Button.tsx
> +    buttonType?: 'primary' | 'secondary' | 'secondary2';
added

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Components/Title/Title.module.scss
> +    // margin: auto;
deleted

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Components/Title/Title.tsx
> +        </div>
thanks, i fixed it

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Components/Title/Title.tsx
> +    if (title === undefined) {
deleted

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Components/AddPost/AddPost.tsx
> +            {/* <div className = {style.addpost}>
Oops.. sorry, this is not a component, but a page. In the future, this page will have a form for adding posts. Right now I used it to test the buttons. Please ignore this page, it will be needed later. I moved it to Pages.

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Pages/SignIn/SignIn.tsx
> +        <>
Nothing, it's a mistake, i fixed it

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Pages/SignUp/SignUp.tsx
> +        <>
Nothing, it's a mistake, i fixed it

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Pages/Home/Home.tsx
> +            {/* <Input title = {'Name'} placeholder = {'Your name'} type = {'password'}/> */}
deleted

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Pages/AllPosts/AllPosts.tsx
> +// import { useNavigate } from "react-router-dom";
deleted

2024-12-17 17:53 UTC, Dmirovna90 commented on my-app/src/Pages/AllPosts/AllPosts.tsx
> +    const [results, setPosts] = useState([]);
fixed it

2024-12-23 15:11 UTC, Dmirovna90 commented
@PavelYermakov1 How about checking my homework? I added fix a week ago

2024-12-24 08:33 UTC, PavelYermakov1 commented
> @PavelYermakov1 How about checking my homework? I added fix a week ago

I wish I could! But you can ask this question to TeachMeSkills managers.

2024-12-30 22:46 UTC, Mukhamed-Talaspaev requested changes

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/README.md
> +# React + TypeScript + Vite
rewrite readme file

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/public/vite.svg
remove unnecessary svg

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/Button/Button.tsx
> +        <button className = {style[buttonType]} disabled= {isDisabled} onClick = {() => console.log('click')}>
remove mocked function onClick = {() => console.log('click')} use function from props instead

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/CardPost/CardPostBig/CardPostBig.tsx
> +import style from './CardPostBig.module.scss';
style is object and if you have a lot classes which are used in your component you can destructure it
as example
const { wrapper, wrap, wraptextcontent  } = styles;

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/CardPost/CardPostMiddle/CardPostMiddle.tsx
> +
remove gaps

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/Header/Header.tsx
> +            </div>
show this only for authorized user, get information about person from Api, endpoint
/auth/users/me/

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/Navbar/Navbar.tsx
> +                <NavLink to = '/user' className = {style.userPoint} onClick={() => dispatch(toggleActive())}><User userName= {'Artem Malkin'}/></NavLink>
create one function const  toggleSideBar = () => dispatch(toggleActive()) and use it for all navlinks

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/Navbar/Navbar.tsx
> +                <button className = {style.buttonTheme} onClick={() => dispatch(switchTheme("dark"))}> <Dark /></button>
create one function const toggleTheme = (theme) => {theme ==="light"? dispatch(switchTheme("light"):dispatch(switchTheme("dark"))}

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/Tabs/TabContent/TabContent.tsx
> +        // '3voluptate autem, officia tempore maxime cum, error nam odio!'
remove it

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/Template/Template.tsx
> +                {props?.button}
instead just use children and where you use Template. Place markup inside the Template tag .

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Pages/AllPosts/AllPosts.tsx
> +    return (
use asynkthunk instead of this

2024-12-30 22:46 UTC, Mukhamed-Talaspaev commented on my-app/src/Pages/SelectedPost/SelectedPost.tsx
> +
the same as comment above

2025-01-09 16:00 UTC, cherkanovart commented on my-app/src/Pages/SearchResults/SearchResults.tsx
> +        fetch('https://studapi.teachmeskills.by/blog/posts/?author__course_group=14&format=json&limit=9')
it's always better to move such code like fetch to a function (for example api folder). ```author__course_group```
```format``` and ```limit``` should be configurable

2025-01-09 16:00 UTC, cherkanovart commented on my-app/src/Pages/AllPosts/AllPosts.tsx
> +        e.preventDefault();
if you already know about useCallbacks, it's better to write such places with useCallback hook

2025-01-09 16:00 UTC, cherkanovart commented on my-app/src/Pages/AllPosts/AllPosts.tsx
> +    const renderPageNumber = () => {
if you already know about useMemo or useCallbacks, it's better to wrap such functions in one of these hooks

2025-01-09 16:00 UTC, cherkanovart commented on my-app/src/Components/Navbar/Navbar.tsx
>                  {/* <NavLink to = '/add-post' className = {style.menuPoint} onClick={() => dispatch(toggleActive())}>Add Post</NavLink> */}
please remove waste commits

2025-01-09 16:00 UTC, cherkanovart commented on my-app/src/Components/Navbar/Navbar.tsx
> +                <NavLink to = '/user' className = {style.userPoint} onClick = {toggleSideBar}><User userName= {'Artem Malkin'}/></NavLink>
please remove unnecessary spaces everywhere. so instead of onClick = {toggleSideBar} u should write onClick={toggleSideBar}

2025-01-10 14:52 UTC, cherkanovart requested changes
also if possible, can you please provide me your telegram, just want to ask you a couple of questions about this project to clarify the project statement

2025-01-10 14:52 UTC, cherkanovart commented on my-app/src/Pages/SearchResults/SearchResults.tsx
> +                        <CardPostSearch id ={id} image ={image} date = {date} title = {title}/>
it seems to me, the code style is wrong. please add spaces

2025-01-10 17:09 UTC, Dmirovna90 commented
> also if possible, can you please provide me your telegram, just want to ask you a couple of questions about this project to clarify the project statement

my telegram - @Darya_Vl. Thanks for checking my homework. I will correct the comments on Saturday-Sunday.

2025-01-12 09:23 UTC, Dmirovna90 commented on my-app/src/Pages/SearchResults/SearchResults.tsx
> +        fetch('https://studapi.teachmeskills.by/blog/posts/?author__course_group=14&format=json&limit=9')
This is homework 42, I had to make a visualization of this page without setting up a search. During the following homeworks this page is not needed, the display of search results is configured through page All Posts

2025-01-13 16:13 UTC, Mukhamed-Talaspaev commented on my-app/src/Components/Title/Title.module.scss
> +    // margin: auto;
done

2025-01-13 17:13 UTC, Mukhamed-Talaspaev approved these changes

2025-01-13 17:46 UTC, merged